name: Push Notification to Feishu
on:
  push:
    branches:
      - main  # 或者你要监听的分支，比如 'master'
jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
    - name: Send message to Feishu
      run: |
        curl -X POST https://open.feishu.cn/open-apis/bot/v2/hook/8bfe55f6-afce-418d-a8ac-3346262417e6 \
        -H "Content-Type: application/json" \
        -d '{
              "msg_type": "text",
              "content": {
                "text": "代码已推送到 main 分支！"
              }
            }'
